language: java
jdk:
  - oraclejdk7
addons:
  firefox: "34.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd ./cucumber-test/
script:
  - pwd
  - curl http://yaowenjie.github.io
  - gradle test
